Update patch set 2
Patch Set 2:

> Mind giving a reason for why not making the return type bool and instead go with the C-style return?

Sure!  I actually started off with bool as the return type and I may be mistaken, but it looks to me like JNIHelp.h has to be C clean: https://cs.corp.google.com/android/libnativehelper/include/nativehelper/JNIHelp.h?l=20

Certainly introducing bool into that header seems to break a lot of C code, e.g.
   In file included from libcore/ojluni/src/main/native/DatagramDispatcher.c:45:
   libnativehelper/include/nativehelper/JNIHelp.h:99:1: error: unknown type name 'bool'

So I took the path of least resistance (and similarity with other methods) and went with int.

Patch-set: 2
Reviewer: Gerrit User 1334152 <1334152@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0