Update patch set 6
Patch Set 6:

Still fails actually.

Buildbot Version: androidbuild_buildbot_20181030.00_RC00
Machine: prod14-2jk3
make -j80 PRODUCT-aosp_cf_x86_phone-userdebug showcommands dist DIST_DIR=/buildbot/dist_dirs/aosp-master-linux-aosp_cf_x86_phone-userdebug/P6982668/0 platform_tests tests
FAILED: out/soong/.intermediates/libnativehelper/libnativehelper_compat_libc++/android_x86_core_shared/obj/libnativehelper/JNIHelp.o
PWD=/proc/self/cwd prebuilts/clang/host/linux-x86/clang-r339409b/bin/clang++ -c -Ilibnativehelper/header_only_include -Ilibnativehelper/include -Ilibnativehelper/header_only_include -Ilibnativehelper/platform_include -Ilibnativehelper -D__ANDROID_API__=19 -msse3 -mstackrealign -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Wimplicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined -Wno-zero-as-null-pointer-constant -Wno-deprecated-register -Wno-sign-compare -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -m32 -march=prescott -isystem prebuilts/ndk/current/sources/cxx-stl/llvm-libc++/include -isystem prebuilts/ndk/current/sources/cxx-stl/llvm-libc++abi/include -isystem prebuilts/ndk/current/sources/android/support/include -isystem out/soong/ndk/sysroot/usr/include -isystem out/soong/ndk/sysroot/usr/include/i686-linux-android -isystem prebuilts/ndk/current/platforms/android-19/arch-x86/usr/include -Werror -target i686-linux-android -Bprebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9/x86_64-linux-android/bin -DANDROID_STRICT -fPIC -std=gnu++14 -Wsign-promo -Wno-inconsistent-missing-override -Wno-null-dereference -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next -fvisibility-inlines-hidden -fno-rtti -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-null-pointer-arithmetic -Wno-enum-compare -Wno-enum-compare-switch -Wno-c++98-compat-extra-semi -Wno-self-assign-overloaded -Wno-constant-logical-operand -Wno-return-std-move-in-c++11 -Wno-dangling-field -MD -MF out/soong/.intermediates/libnativehelper/libnativehelper_compat_libc++/android_x86_core_shared/obj/libnativehelper/JNIHelp.o.d -o out/soong/.intermediates/libnativehelper/libnativehelper_compat_libc++/android_x86_core_shared/obj/libnativehelper/JNIHelp.o libnativehelper/JNIHelp.cpp
libnativehelper/JNIHelp.cpp:360:12: error: cannot initialize return object of type 'const char *' with an rvalue of type 'int'
return strerror_r(errnum, buf, buflen);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Patch-set: 6
Reviewer: Gerrit User 1047769 <1047769@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0